export default [
  {
    planNumber: 10024,
    type: 0,
    description: 'Normal Credit',
    effectiveFrom: null,
    effectiveTo: null,
    periodType: null,
    periodDuration: 0,
    apr: 29.9,
    priority: 3,
    active: true,
    interestType: 0,
    interestDescription: null,
    basketValue: 0,
  },
  {
    planNumber: 10022,
    type: 0,
    description: '12 Months Buy Now Pay Later',
    effectiveFrom: null,
    effectiveTo: null,
    periodType: null,
    periodDuration: 0,
    apr: 29.9,
    priority: 1,
    active: true,
    interestType: 0,
    interestDescription: null,
    basketValue: 0,
  },
  {
    planNumber: 10023,
    type: 0,
    description: '6 Months Buy Now Pay Later',
    effectiveFrom: null,
    effectiveTo: null,
    periodType: null,
    periodDuration: 0,
    apr: 29.9,
    priority: 2,
    active: true,
    interestType: 0,
    interestDescription: null,
    basketValue: 0,
  },
]
