export interface ErrorDetail<ErrorAdvice> {
  type: string
  advice: ErrorAdvice
  customerId?: string
}

export interface ErrorResponse<ErrorAdvice> {
  error: {
    status?: string
    message: string
    details: ErrorDetail<ErrorAdvice>[]
  }
}

export enum InitSnapshotAPINonFatalErrorAdvice {
  // status 200
  STOCK_HOLD_PARTIAL_ALLOCATION = 'STOCK_HOLD_PARTIAL_ALLOCATION',
  NECTAR_POINTS_CALCULATION_ERROR = 'NECTAR_POINTS_CALCULATION_ERROR',
}

export enum InitSnapshotAPIErrorAdvice {
  // Validation error (status 400)
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',
  PAYMENT_INVALID_IPADDRESS = 'PAYMENT_INVALID_IPADDRESS',
  PAYMENT_INVALID_SALESCHANNEL = 'PAYMENT_INVALID_SALESCHANNEL',
  PAYMENT_INVALID_SOURCEDATA = 'PAYMENT_INVALID_SOURCEDATA',
  PAYMENT_INVALID_FORENAME = 'PAYMENT_INVALID_FORENAME',
  PAYMENT_INVALID_SURNAME = 'PAYMENT_INVALID_SURNAME',
  PAYMENT_INVALID_EMAIL = 'PAYMENT_INVALID_EMAIL',
  PAYMENT_INVALID_MOBILE_PHONE = 'PAYMENT_INVALID_MOBILE_PHONE',
  PAYMENT_INVALID_HOME_PHONE = 'PAYMENT_INVALID_HOME_PHONE',
  PAYMENT_INVALID_TITLE = 'PAYMENT_INVALID_TITLE',
  PAYMENT_PHONE_MISSING = 'PAYMENT_PHONE_MISSING',
  PAYMENT_MISSING_LINES = 'PAYMENT_MISSING_LINES',
  PAYMENT_MISSING_ADDRESSES = 'PAYMENT_MISSING_ADDRESSES',
  PAYMENT_MISSING_BILLING_ADDRESS = 'PAYMENT_MISSING_BILLING_ADDRESS',
  PAYMENT_MISSING_CUSTOMER_DETAILS = 'PAYMENT_MISSING_CUSTOMER_DETAILS',
  STOCK_HOLD_QUANTITY_ERROR = 'STOCK_HOLD_QUANTITY_ERROR',
  USER_COOKIES_MISSING = 'USER_COOKIES_MISSING',
  SOURCE_ERROR = 'SOURCE_ERROR',
  INCOMPLETE_BOOKING = 'INCOMPLETE_BOOKING',

  // Failed Dependency (Status 424)
  STOCK_HOLD_FAILED_ALLOCATION = 'STOCK_HOLD_FAILED_ALLOCATION',

  // Internal System Error (Status 500)
  PAYMENT_INITIALISATION_ERROR = 'PAYMENT_INITIALISATION_ERROR',
  ORDER_SNAPSHOT_UPDATE_FAILED = 'ORDER_SNAPSHOT_UPDATE_FAILED',
  STOCK_HOLD_SERVICE_ERROR = 'STOCK_HOLD_SERVICE_ERROR',
  STOCK_HOLD_PRODUCT_OR_STOREID_ERROR = 'STOCK_HOLD_PRODUCT_OR_STOREID_ERROR',
  STOCK_HOLD_UNABLE_TO_RESERVE = 'STOCK_HOLD_UNABLE_TO_RESERVE',
  STOCK_HOLD_PARTIAL_ALLOCATION_DISALLOWED = 'STOCK_HOLD_PARTIAL_ALLOCATION_DISALLOWED',
  USER_DETAILS_RETRIEVE_ERROR = 'USER_DETAILS_RETRIEVE_ERROR',

  // Request Timeout (Status 504)
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
}

export enum GetSnapshotAPIErrorAdvice {
  REQUEST_UNAUTHORISED = 'REQUEST_UNAUTHORISED',
  ORDER_SNAPSHOT_NOT_FOUND = 'ORDER_SNAPSHOT_NOT_FOUND',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum PrepareForCheckoutAPIErrorAdvice {
  MISSING_BOOKING_ID = 'MISSING_BOOKING_ID',
}

export type InitialiseSnapshotAPIErrorResponse = ErrorResponse<InitSnapshotAPIErrorAdvice>

export type GetSnapshotAPIErrorResponse = ErrorResponse<GetSnapshotAPIErrorAdvice>

export enum CreateFulfilmentAPIErrorAdvice {
  POSTCODE_MISMATCH = 'POSTCODE_MISMATCH',
  STOCK_HOLD_EXCLUSION_FAILURE = 'STOCK_HOLD_EXCLUSION_FAILURE',
  STOCK_HOLD_FAILED_ALLOCATION = 'STOCK_HOLD_FAILED_ALLOCATION',
}
