const ErrorCodes = {
  200: 'OK',
  400: 'VALIDATION_ERROR',
  401: 'AUTHORIZATION_ERROR',
  409: 'CONFLICT_ERROR',
  424: 'APPLICATION_ERROR',
  500: 'INTERNAL_SERVER_ERROR',
  504: 'GATEWAY_TIMEOUT_ERROR',
}

export default ErrorCodes
