export enum PaymentAlerts {
  PAYPAL_INCOMPATIBLE = 'PAYPAL_INCOMPATIBLE',
  APPLE_PAY_INCOMPATIBLE = 'APPLE_PAY_INCOMPATIBLE',
  PAYPAL_UNAVAILABLE = 'PAYPAL_UNAVAILABLE',
  APPLE_PAY_UNAVAILABLE = 'APPLE_PAY_UNAVAILABLE',
  APPLE_PAY_OVER_LIMIT = 'APPLE_PAY_OVER_LIMIT',
  PLACE_ORDER_ERROR = 'PLACE_ORDER_ERROR',
  SELECTED_DATACASH_PAYMENT_NOT_AVAILABLE = 'SELECTED_DATACASH_PAYMENT_NOT_AVAILABLE',
  SELECTED_DATACASH_PAYMENT_NOT_AVAILABLE_SAVED_CARD = 'SELECTED_DATACASH_PAYMENT_NOT_AVAILABLE_SAVED_CARD',
  ALL_DATACASH_PAYMENTS_NOT_AVAILABLE = 'ALL_DATACASH_PAYMENTS_NOT_AVAILABLE',
}
